### ISSUE TITLE
issues with README

### ISSUE THREAD

**Issue by DavidTeju** [grayoj/gitchat#2]
## README.md
Installation guide and contribution guidelines should be in README.md under their own section. There's no reason to have them as is. Very obscure.  
In the README document, all the links are broken. Including the link to the FAQ and the link to profiles; those lead to the homepage of github.

**Comment by grayoj** [comment]
I am very sorry for that. All these errors stated in the issue you opened will be attended to, and done properly on or before Friday this week. Thank you very much Mr David!
